name: CI Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build (windows-latest)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build release
        run: cargo build --release

      - name: Create artifacts dir
        run: New-Item -ItemType Directory -Force -Path artifacts

      - name: Copy exe to artifacts
        run: Copy-Item -Path target\release\MicVolumeHolder.exe -Destination artifacts\MicVolumeHolder.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicVolumeHolder-windows
          path: artifacts/MicVolumeHolder.exe

  release:
    name: Create GitHub Release
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: MicVolumeHolder-windows

      - name: List files (debug)
        run: ls -la

      - name: Create GitHub release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          name: MicVolumeHolder ${{ github.ref_name }}
          files: MicVolumeHolder.exe
